# yaml-language-server: $schema=https://aka.ms/winget-manifest.version.1.6.0.schema.json

PackageIdentifier: Locomorange.UIAutomationMCP
PackageVersion: 0.1.0  # This will be updated by CI
DefaultLocale: en-US
ManifestType: version
ManifestVersion: 1.6.0
---
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.6.0.schema.json

PackageIdentifier: Locomorange.UIAutomationMCP
PackageVersion: 0.1.0  # This will be updated by CI
PackageLocale: en-US
Publisher: Locomorange
PublisherUrl: https://github.com/locomorange/UIAutomationMCP
PublisherSupportUrl: https://github.com/locomorange/UIAutomationMCP/issues
PackageName: UIAutomation MCP Server
PackageUrl: https://github.com/locomorange/UIAutomationMCP
License: MIT
LicenseUrl: https://github.com/locomorange/UIAutomationMCP/blob/main/LICENSE
Copyright: Copyright (c) 2025 Locomorange
ShortDescription: Windows UI Automation Model Context Protocol (MCP) server with Native AOT optimization
Description: |-
  UIAutomationMCP is a high-performance MCP server that provides Windows UI Automation capabilities.
  Features include:
  - Native AOT compilation for ultra-fast startup (~400ms)
  - Shared runtime architecture for efficient deployment
  - Full Windows UI Automation API support
  - Element search, interaction, and monitoring capabilities
  - Process isolation for stability and security
  - MessagePack-based IPC for optimal performance
Moniker: uiautomation-mcp
Tags:
- mcp
- ui-automation
- windows
- accessibility
- testing
- automation
- native-aot
- dotnet
ReleaseNotesUrl: https://github.com/locomorange/UIAutomationMCP/releases/latest
ManifestType: defaultLocale
ManifestVersion: 1.6.0
---
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: Locomorange.UIAutomationMCP
PackageVersion: 0.1.0  # This will be updated by CI
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.19041.0
InstallerType: zip
Scope: user
InstallModes:
- interactive
- silent
UpgradeBehavior: install
Dependencies:
  PackageDependencies:
  - PackageIdentifier: Microsoft.DotNet.DesktopRuntime.9
    MinimumVersion: 9.0.0
  WindowsFeatures:
  - Microsoft-Windows-Subsystem-Linux
  WindowsLibraries:
  - Microsoft.VCRedist.2015+.x64
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/locomorange/UIAutomationMCP/releases/download/v0.1.0/UIAutomationMCP-v0.1.0-win-x64.zip
  InstallerSha256: PLACEHOLDER_SHA256  # This will be updated by CI
  NestedInstallerType: portable
  NestedInstallerFiles:
  - RelativeFilePath: Server\uiautomation-mcp.exe
    PortableCommandAlias: uiautomation-mcp
- Architecture: arm64
  InstallerUrl: https://github.com/locomorange/UIAutomationMCP/releases/download/v0.1.0/UIAutomationMCP-v0.1.0-win-arm64.zip
  InstallerSha256: PLACEHOLDER_SHA256  # This will be updated by CI
  NestedInstallerType: portable
  NestedInstallerFiles:
  - RelativeFilePath: Server\uiautomation-mcp.exe
    PortableCommandAlias: uiautomation-mcp
ManifestType: installer
ManifestVersion: 1.6.0