# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: Locomorange.UIAutomationMCP
PackageVersion: 0.1.0  # This will be updated by CI
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.19041.0
InstallerType: zip
Scope: user
InstallModes:
- interactive
- silent
UpgradeBehavior: install
Dependencies:
  PackageDependencies:
  - PackageIdentifier: Microsoft.DotNet.DesktopRuntime.9
    MinimumVersion: 9.0.0
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/locomorange/uiautomation-mcp/releases/download/v0.1.0/UIAutomationMCP-v0.1.0-win-x64.zip
  InstallerSha256: PLACEHOLDER_SHA256  # This will be updated by CI
  NestedInstallerType: portable
  NestedInstallerFiles:
  - RelativeFilePath: Server\uiautomation-mcp.exe
    PortableCommandAlias: uiautomation-mcp
- Architecture: arm64
  InstallerUrl: https://github.com/locomorange/uiautomation-mcp/releases/download/v0.1.0/UIAutomationMCP-v0.1.0-win-arm64.zip
  InstallerSha256: PLACEHOLDER_SHA256  # This will be updated by CI
  NestedInstallerType: portable
  NestedInstallerFiles:
  - RelativeFilePath: Server\uiautomation-mcp.exe
    PortableCommandAlias: uiautomation-mcp
ManifestType: installer
ManifestVersion: 1.6.0